@BG-Tec-HostAddress = https://localhost:7024

###
POST https://localhost:7024/check-in
Accept: application/json
Content-Type: application/json
 {
  "forename": "Jane",
  "surname": "Doe",
  "dob": "1992-01-01",
  "documentNumber": "zzzzzzzzzzzzzzzz",
  "flightId": 1552
 }

 ###
@id=1
GET https://localhost:7024/traveller/{{id}}

###

GET https://localhost:7024/traveller/search?name=J

###
