@BG-Tec-HostAddress = https://localhost:7024

###
POST https://localhost:7024/check-in
Accept: application/json
Content-Type: application/json
 {
  "forename": "Jack",
  "surname": "Doe",
  "dob": "1982-01-01",
  "documentNumber": "111111111111111",
  "flightId": 1552
 }

 ###
@id=1
GET https://localhost:7024/traveller/{{id}}

###

GET https://localhost:7024/traveller/search?name=j

###
