// <auto-generated />
using System;
using BG_Tec_Assesment_Minimal_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BG_Tec_Assesment_Minimal_Api.Migrations
{
    [DbContext(typeof(TravellerAPIDbContext))]
    [Migration("20251128153905_Add concurrency Token")]
    partial class AddconcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BG_Tec_Assesment_Minimal_Api.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1552
                        },
                        new
                        {
                            Id = 1553
                        },
                        new
                        {
                            Id = 1554
                        });
                });

            modelBuilder.Entity("BG_Tec_Assesment_Minimal_Api.Models.Traveller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("DocumentNumberSHA")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumberSHA")
                        .IsUnique();

                    b.ToTable("Travellers");
                });

            modelBuilder.Entity("FlightTraveller", b =>
                {
                    b.Property<int>("FlightsId")
                        .HasColumnType("int");

                    b.Property<int>("TravellersId")
                        .HasColumnType("int");

                    b.HasKey("FlightsId", "TravellersId");

                    b.HasIndex("TravellersId");

                    b.ToTable("FlightTraveller");
                });

            modelBuilder.Entity("FlightTraveller", b =>
                {
                    b.HasOne("BG_Tec_Assesment_Minimal_Api.Models.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BG_Tec_Assesment_Minimal_Api.Models.Traveller", null)
                        .WithMany()
                        .HasForeignKey("TravellersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
